version: '3'

services:

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    deploy:
      mode: Replicated
      replicas: 1
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Auth
    
